;//
//  Created by Roberto Giessler
//  All rights reserved
//

// Apple
#import <Foundation/Foundation.h>

// Third party
// Categories
#import "NSObject+AutoMagicCoding.h"

// Disable AutoMagicCoding exceptions
#define AMC_NO_THROW

// MARK: Constants
static NSString* const kRCCPersistentObjectErrorDomain = @"com.elisabit.RCC.RCCPersistentObject";

/**
 A RCCUbiquitousObject acts as a root class for subclassing.
 It includes information such as a timestamp and a deletion flag for uniqueing and updating in cooperation with a synced store.
 RCCUbiquitousObject objects and its subclasses are typically generated by RCCUbiquitousObjectsController which handles persistence and syncing as well.
*/

@interface RCCUbiquitousObject : NSObject
// MARK: Properties
@property (readonly) NSString       *uid;
@property (readonly) NSTimeInterval  timestamp;
@property (assign)   BOOL            needsDeletion;

// MARK: Init
/** 
 @return Newly initialized RCCUbiquitousObject object.
 */
- (id)init;

// MARK: Utility
/**
 This method must not be called directly but is beeing used by the RCCUbiquitousObjectsController class instead.
 
 Updates the timestamp before the object is beeing persisted to a local or synced store.
*/
- (void)updateTimestamp;
@end

@interface RCCUbiquitousObject(RCCUbiquitousObjectTemplateMethods)
/**
 Override this method and return an NSArray of NSString objects containing the names of the propertys that should be checked for uniqueness before the object is beeing stored.
 */
- (NSArray *)uniquePropertys;
@end
